name: redwatch
version: "1.0.0"
config-version: 2

profile: redwatch_profile

model-paths: ["models"]

models:
  redwatch:
    raw_clean:
      +materialized: view
    cluster_clean:
      +materialized: view
    clean_table:
      +materialized: table
