name: redwatch
version: "1.0.0"
config-version: 2

profile: redwatch_profile

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  redwatch:
    +materialized: view

    staging:
      +materialized: view

    marts:
      +materialized: incremental
      +incremental_strategy: delete+insert

    kpi:
      +materialized: incremental
      +incremental_strategy: delete+insert
